# -*- encoding: UTF-8 -*-

# file generated by convert_i18n_yaml.py from i18n.yaml

languages = \
    {
        'en': {
            'as_a': [u'As'],
            'i_wanna': [u'I want'],
            'so_that': [u'So that'],
            'and': [u'And'],
            'background': [u'Background'],
            'but': [u'But'],
            'examples': [u'Examples', u'Scenarios'],
            'feature': [u'Feature'],
            'given': [u'Given'],
            'name': [u'English'],
            'native': [u'English'],
            'scenario': [u'Scenario'],
            'scenario_outline': [u'Scenario Outline', u'Scenario Template'],
            'then': [u'Then'],
            'when': [u'When'],
        },

        'pt': {
            'as_a': [u'Como'],
            'i_wanna': [u'Quero'],
            'so_that': [u'Para'],
            'and': [u'E'],
            'background': [u'Contexto'],
            'but': [u'Mas'],
            'examples': [u'Exemplos'],
            'feature': [u'Funcionalidade'],
            'given': [u'Dado', u'Dada', u'Dados', u'Dadas'],
            'name': [u'Portuguese'],
            'native': [u'portugu\xeas'],
            'scenario': [u'Cen\xe1rio', u'Cenario'],
            'scenario_outline': [u'Esquema do Cen\xe1rio', u'Esquema do Cenario'],
            'then': [u'Ent\xe3o', u'Entao'],
            'when': [u'Quando'],
        },
    }
